openapi: "3.1.0"
info:
  title: 情報管理システム
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /sample/{id}:
    get:
      description: サンプル説明
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: 正常系
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sample'
        default:
          description: 異常系
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Other'
components:
  schemas:
    Sample:
      type: "object"
      required:
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 100
        name:
          type: "string"
          example: "anti-paper"
        status:
          type: "string"
          description: "状態"
          enum:
            - "有効"
            - "非有効"
    Other:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
          example: 404
        message:
          type: "string"
          example: "Not found."
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
